do the thing + create axios instance
codersforcauses/csf pull request #113
Opened 2023-07-10 09:46 UTC by urwrstkn8mare

2023-07-10 11:13 UTC, ChantelleKerr requested changes
Added some suggestions for UI

2023-07-10 11:13 UTC, ChantelleKerr commented on client/src/views/EventsView.vue
> +  <p v-else class="pt-6 mx-3">Loading...</p>
Something like this could be cool :)
https://vuetifyjs.com/en/components/progress-circular/

2023-07-10 13:39 UTC, urwrstkn8mare commented on client/src/views/EventsView.vue
> +      </p>
i did it but have a look if its good enough. i didn't go that hard on the styling.

2023-07-11 12:04 UTC, ChantelleKerr approved these changes
Good job! Approved

2023-07-11 13:11 UTC, merged