I105 export django model data
codersforcauses/csf pull request #139
Opened 2023-07-15 04:03 UTC by makon1234

## Change Summary
Can now export user data from django endpoints. Password not included and users without consent are not exported. 

### Change Form
na

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
no

2023-07-16 01:48 UTC, ChantelleKerr requested changes
I gget a few errors

Exporting mileage data:
<img width="1492" alt="Screen Shot 2023-07-16 at 9 46 20 am" src="https://github.com/codersforcauses/csf/assets/45170409/3d8a32ea-004c-45ae-98c0-bb91c6c1adf1">

Exporting Team data:
<img width="868" alt="Screen Shot 2023-07-16 at 9 46 05 am" src="https://github.com/codersforcauses/csf/assets/45170409/d622d0bc-c673-4e6b-a009-f331566c7f1e">

2023-07-16 01:48 UTC, ChantelleKerr commented on server/api/actions.py
> +    replacements = {'team_id': 'team_id__name', 'user': 'user__frist_name'}
it should be "user__first_name"

2023-07-16 07:16 UTC, makon1234 commented on server/api/actions.py
> +    replacements = {'team_id': 'team_id__name', 'user': 'user__frist_name'}
my bad, its been fixed

2023-07-16 07:48 UTC, ChantelleKerr approved these changes
Great job! Approved

2023-07-16 07:53 UTC, makon1234 commented
Hi, I don't think I have fixed all the errors yet, I still need to do exporting team data, that one is easy but in the Users.csv, you want team name instead of team_id right, right now it changes all the team_id so.... we still need work on that

2023-07-16 08:05 UTC, ChantelleKerr commented
> Hi, I don't think I have fixed all the errors yet, I still need to do exporting team data, that one is easy but in the Users.csv, you want team name instead of team_id right, right now it changes all the team_id so.... we still need work on that

oops, my bad. Let me know when its all good

2023-07-17 03:31 UTC, makon1234 commented
Hi, it should be all good now. Could you please confirm?

2023-07-17 09:01 UTC, ChantelleKerr approved these changes
Works well! Good job :)

Approved.

2023-07-17 09:06 UTC, merged