i104 Add Alerts
codersforcauses/csf pull request #146
Opened 2023-07-15 06:01 UTC by wuryantoAji

## Change Summary
Adding alert component 

### Change Form

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
It seems I can't login to the web using the django superuser so I created two recording both is shown when login failed but one gives error alert while the other one gives success alert
https://drive.google.com/file/d/1xINVS2UfsVpXjlrvOhjGDtI6QdD5SO31/view?usp=sharing -> error alert
https://drive.google.com/file/d/1_5DTzAuyHw7hzBpCfbTEt2D7ebfcMz2S/view?usp=sharing -> success alert

How I used the alert component in login 
`<template ...

<RequestAlert
      v-if="alert.status"
      :color="alert.color"
      :icon="alert.icon"
      :message="alert.message"   
/>
</template>

<script ....

import RequestAlert from './RequestAlert.vue'

const alert = ref({
  status: '',
  color: '',
  icon: '',
  message: ''
})

async function.....
    alert.value.status='success'
    alert.value.color='success'
    alert.value.icon='$success'
    alert.value.message='Login Success'`

2023-07-15 09:39 UTC, ChantelleKerr requested changes
Please add alert to all backend requests as discussed, thank you :)

2023-07-19 03:03 UTC, ChantelleKerr requested changes
Please do for all requests. Event, Team, Mileage, User settings page.

Merge main into your branch first because a few changes have been added.

2023-07-19 06:10 UTC, wuryantoAji commented
Hello, I think I have put all notify on the function that calls backend. Please kindly tell me if there is something that I miss or if a notification is too annoying/not necessary for the function. thanks in advance

2023-07-19 11:34 UTC, ChantelleKerr requested changes
We can remove two of the successful one because we dont want it to pop up all the time. Also, the position of the notification on mobile doesnt look right. You could probably make the notification have a smaller width.

Good job its working as expected :)

2023-07-19 11:34 UTC, ChantelleKerr commented on client/src/stores/team.ts
> +          })
We probably dont need this alert. Keep the unsuccessful one though

2023-07-19 11:34 UTC, ChantelleKerr commented on client/src/stores/team.ts
> +              text: 'Get Team Successful'
We dont need this - keep unsuccessful one though

2023-07-19 12:18 UTC, ChantelleKerr commented
Is this ready for review again? :)

2023-07-19 12:36 UTC, wuryantoAji commented
not yet chantelle, I will re-request for review if it's ready

2023-07-19 14:03 UTC, ChantelleKerr approved these changes
looks good, nice work

2023-07-19 14:05 UTC, merged