I102 protect user and team dashboard pages
codersforcauses/csf pull request #148
Opened 2023-07-15 06:31 UTC by Alex-Hawking

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
Made it so that use cannot redirect to team and dashboard pages if not logged
Login modal opens if redirect fails

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2023-07-15 10:07 UTC, ChantelleKerr requested changes
very quick fixes and I can approve.

Good job!

2023-07-15 10:07 UTC, ChantelleKerr commented on client/src/components/LoginModal.vue
>  const { mobile } = useDisplay()
we can remove the line with useDisplay

2023-07-15 10:07 UTC, ChantelleKerr commented on client/src/components/LoginModal.vue
> +const router = useRouter()
Since this is not used we can remove it

2023-07-15 10:07 UTC, ChantelleKerr commented on client/src/components/LoginModal.vue
> +const ModalStateStore = useModalStateStore()
is this used anywhere?

2023-07-15 10:07 UTC, ChantelleKerr commented on client/src/components/LoginModal.vue
> +
remove console log

2023-07-15 13:25 UTC, Alex-Hawking commented
All changes should be done

2023-07-16 01:20 UTC, ChantelleKerr approved these changes
Good job! Approved

2023-07-16 01:21 UTC, merged