app icon and name fix
codersforcauses/csf pull request #218
Opened 2023-07-20 02:34 UTC by YunnTun

## Change Summary

**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form

**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information

**[Is there anything in particular in the review that I should be aware of?]**

2023-07-20 15:50 UTC, ChantelleKerr requested changes
Remove ReloadPWA template

2023-07-20 15:50 UTC, ChantelleKerr commented on client/vite.config.ts
> -          //   sizes: "512x512",
remove comments

2023-07-22 07:42 UTC, RadioArsenic approved these changes
Good work!

2023-07-22 08:05 UTC, ChantelleKerr approved these changes
nice

2023-07-22 09:29 UTC, merged