I140 make leaderboard page
codersforcauses/csf pull request #264
Opened 2023-07-22 09:13 UTC by HuxleyBerry

## Change Summary

**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form

**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information

**[Is there anything in particular in the review that I should be aware of?]**

2023-07-23 02:33 UTC, ChantelleKerr requested changes
Some changes - its looking very nice!
While your here can you please make the events and leaderboard banner the same height? I like the height of the leaderboard :)

2023-07-23 02:33 UTC, ChantelleKerr commented on client/src/views/LeaderboardView.vue
> +      </tr>
I would try make the styling slightly different than the other rows

2023-07-23 02:33 UTC, ChantelleKerr commented on client/src/views/LeaderboardView.vue
> +  </div>
the colour looks different compared to other pages.

2023-07-23 02:33 UTC, ChantelleKerr commented on client/src/views/LeaderboardView.vue
> +    >
needs slightly more spacing top and bottom

2023-07-23 02:33 UTC, ChantelleKerr commented on server/api/users/migrations/0009_user_total_mileage.py
> +    ]
I would suggest deleting 0009 and 0011 migrations - merge main into this branch. and then makemigrations again. Main already has a 0009 and 0010.

From my experience on the wais project deleting migration files that has already been on deployed causes problems for production version.

2023-07-24 02:43 UTC, ChantelleKerr commented
Might have to merge main into your branch. You could change how you get the total mileage since you have it stored in the user table

2023-07-24 04:22 UTC, HuxleyBerry commented
> Might have to merge main into your branch. You could change how you get the total mileage since you have it stored in the user table

Hmm, so calling get_mileage() for every user rather than simply accessing the total_mileage field? The latter option should be a lot more efficient I think.

2023-07-24 04:23 UTC, ChantelleKerr commented
> > Might have to merge main into your branch. You could change how you get the total mileage since you have it stored in the user table
> 
> Hmm, so calling get_mileage() for every user rather than simply accessing the total_mileage field? The latter option should be a lot more efficient I think.

Yeah I agree, the graph PR didnt have a total_mileage field so yours works well i think :)

2023-07-24 04:27 UTC, HuxleyBerry commented
However, in the teams case, I realise there is the potential for there to be a discrepancy between the value of total_mileage in the team model, and the sum value obtained by get_mileage(). This is because total_mileage doesn't count mileage achieved before a user joined the team, whereas get_mileage() does. So for consistency, maybe get_mileage() should return the value of total mileage in this case. We wouldn't want the total km value in the team dashboard to be different to what is shown on the leaderboard. The downside to this is that the total implied by the team mileage graph wouldn't match with the total given in the team dashboard. Not sure what to best thing to do is...

2023-07-24 04:32 UTC, HuxleyBerry commented
Perhaps the solution is for the mileage model to have a nullable team field, which records the team (if any) the user was in when the mileage was achieved. I think that will fix everything

...assuming that what we want to do is only count mileage achieved when the user is part of the team

2023-07-24 10:19 UTC, HuxleyBerry commented
Think I'm done now

2023-07-24 14:05 UTC, ChantelleKerr approved these changes
Looks really nice! Good stuff :D

2023-07-24 14:06 UTC, merged