change paragraph
codersforcauses/csf pull request #269
Opened 2023-07-23 13:39 UTC by Alex-Hawking

## Change Summary

Re-wrote the paragraph

### Change Form

**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information

Not sure if the description should have 12 or 14 days? I've put 14 rn

2023-07-23 15:02 UTC, RadioArsenic requested changes
Say it's over a 12 day period so the daily kms make sense, but try to mention somehow that progress resets after 14

2023-07-23 15:09 UTC, RadioArsenic commented
Also remove the added favicon

2023-07-25 03:12 UTC, ChantelleKerr commented on client/src/views/ChallengeView.vue
> +        (Don't worry if you can't complete all the challenges, just do you best!)
should be "just do your best!"

2023-07-25 04:14 UTC, RadioArsenic requested changes
"and watch your progress on your personal dashboard"

Should be your dash not the dash

2023-07-25 04:49 UTC, RadioArsenic approved these changes
Looks good!

2023-07-25 04:57 UTC, merged