i9 create navigation bar
codersforcauses/csf pull request #38
Opened 2023-06-27 14:22 UTC by wuryantoAji

## Change Summary
add navbar components 

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

> any documents where I can put documentation?
> test is only recording of the navbar the recording is in this gdrive https://drive.google.com/file/d/1VYh1PsGkbngIZsPGCjn287MrGk1LgT3Y/view?usp=sharing

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
- needs to comment the `import './assets/main.css'` in main.ts since main.css from vue makes it render incorrectly

2023-06-27 14:51 UTC, ChantelleKerr commented on client/src/components/Navbar.vue
> +</script>
You are using the options API here. We are using the Composition API with Typescript. 

https://vuejs.org/api/sfc-script-setup.html#basic-syntax

2023-06-27 14:56 UTC, ChantelleKerr commented on client/src/components/Navbar.vue
> +    <v-toolbar-title class="hidden-md-and-down">Community Spirit Foundation</v-toolbar-title>
We dont need the title :)

2023-06-27 15:03 UTC, wuryantoAji commented on client/src/components/Navbar.vue
> +    <v-toolbar-title class="hidden-md-and-down">Community Spirit Foundation</v-toolbar-title>
noted, will remove it

2023-06-29 07:19 UTC, ChantelleKerr requested changes
Nice job! It looks really good

Some small changes and vuetify tip ;)

We want to avoid css as much as possible if vuetify can do the same thing

2023-06-29 07:19 UTC, ChantelleKerr commented on client/src/components/NavbarComponents.vue
> +}
You can remove this

2023-06-29 07:19 UTC, ChantelleKerr commented on client/src/components/NavbarComponents.vue
> +}
You can remove this - vuetify does it inline. See here: https://vuetifyjs.com/en/styles/spacing/

2023-06-29 07:19 UTC, ChantelleKerr commented on client/src/components/NavbarComponents.vue
> +          <img id="app" src="@/assets/Footer-min.jpeg" class="border hidden-md-and-up" />
make this into v-img. See below to copy paste

2023-06-29 07:19 UTC, ChantelleKerr commented on client/src/components/NavbarComponents.vue
> +      <v-card class="overall">
you can set color="black" here :)

2023-06-29 07:19 UTC, ChantelleKerr commented on client/src/components/NavbarComponents.vue
> +            <v-btn icon @click="dialog = false" class="hidden-md-and-up menuIcon">
menuIcon not needed

2023-06-29 07:24 UTC, wuryantoAji commented
noted, will fix all of it. thanks for the review Chantelle

2023-06-29 08:25 UTC, ChantelleKerr approved these changes
Great job! Looks amazing. Approved

2023-06-29 08:30 UTC, merged