I32 deployment setup the compose files for production environment
codersforcauses/csf pull request #90
Opened 2023-07-08 06:31 UTC by zhanerken

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2023-07-08 07:17 UTC, frinzekt commented on docker-compose-prod.yml
>        retries: 5
we need 2 files:
- `docker-compose.yml` for local development
- `docker-compose-prod.yml` for production deployment.

2023-07-08 07:58 UTC, jsun1590 approved these changes
LGTM

2023-07-10 05:03 UTC, ChantelleKerr requested changes
Small mistake

2023-07-10 05:03 UTC, ChantelleKerr commented on docker-compose-dev.yml
> +    command: --interval 30
This shouldnt use dockerhub, it build locally

2023-07-10 14:31 UTC, frinzekt commented
You should retain the docker-compose.yml file ... Don't rename it... If you want to rename it, then you'll have to tell everyone the syntax to run the new compose file, which you don't have to if you dont

2023-07-15 05:02 UTC, frinzekt commented on docker-compose.yml
> -    depends_on:
what's the reason for this change?

2023-07-15 05:02 UTC, frinzekt commented on docker/client/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
this file should not exist

2023-07-15 05:03 UTC, frinzekt approved these changes
looks good to me to be merged, you can follow it up with a cleanup pr

2023-07-15 05:54 UTC, merged